project:
  type: website
  output-dir: docs

website:
  title: "DACSS790 Causal Inference Spring 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Tutorial1.qmd
        text: Tutorial1

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


