<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial_5 – DACSS790 Causal Inference Spring 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DACSS790 Causal Inference Spring 2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial1.html"> 
<span class="menu-text">Tutorial1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial2.html"> 
<span class="menu-text">Tutorial2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial3.html"> 
<span class="menu-text">Tutorial3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial4.html"> 
<span class="menu-text">Tutorial4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Tutorial5.html" aria-current="page"> 
<span class="menu-text">Tutorial5</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#front-end-matters" id="toc-front-end-matters" class="nav-link active" data-scroll-target="#front-end-matters">Front-end Matters</a></li>
  <li><a href="#introducing-dataset" id="toc-introducing-dataset" class="nav-link" data-scroll-target="#introducing-dataset">Introducing dataset</a></li>
  <li><a href="#sls" id="toc-sls" class="nav-link" data-scroll-target="#sls">2SLS</a>
  <ul class="collapse">
  <li><a href="#simple-regression-model" id="toc-simple-regression-model" class="nav-link" data-scroll-target="#simple-regression-model">Simple regression model</a></li>
  <li><a href="#multiple-regression-model" id="toc-multiple-regression-model" class="nav-link" data-scroll-target="#multiple-regression-model">Multiple regression model</a></li>
  </ul></li>
  <li><a href="#accessing-instrumental-validity" id="toc-accessing-instrumental-validity" class="nav-link" data-scroll-target="#accessing-instrumental-validity">Accessing Instrumental Validity</a>
  <ul class="collapse">
  <li><a href="#weak-instrument-test" id="toc-weak-instrument-test" class="nav-link" data-scroll-target="#weak-instrument-test">Weak instrument test</a></li>
  <li><a href="#overidentification-test-sargan-hansen" id="toc-overidentification-test-sargan-hansen" class="nav-link" data-scroll-target="#overidentification-test-sargan-hansen">Overidentification test (Sargan-Hansen)</a></li>
  <li><a href="#endogeneity-test-wu-hausman" id="toc-endogeneity-test-wu-hausman" class="nav-link" data-scroll-target="#endogeneity-test-wu-hausman">Endogeneity test (Wu-Hausman)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 5 Instrumental Variables</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Instrumental variable estimation is a crucial tool in causal inference, allowing researchers to address endogeneity and obtain unbiased estimates when treatment assignment is not purely random. This tutorial will guide you through implementing instrumental variable estimation in R using Two-Stage Least Squares (2SLS), as well as testing for endogeneity, weak instruments, and overidentification.</p>
<p>By the end of this tutorial, you will be familiar with:</p>
<p>1.&nbsp;2SLS in R</p>
<p>2.&nbsp;Assessing instrument validity</p>
<section id="front-end-matters" class="level1">
<h1>Front-end Matters</h1>
<p>We use <code>AER</code> package for 2SLS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("AER")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lmtest</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sandwich</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
</div>
</section>
<section id="introducing-dataset" class="level1">
<h1>Introducing dataset</h1>
<p>We use the <code>CigarettesSW</code> data from the <code>AER</code> package. It is a panel data set that contains observations on cigarette consumption and several economic indicators for all 48 continental federal states of the U.S. from 1985 to 1995. We consider data for the cross section of states in 1995 only.</p>
<p>We want to know the relationship between <strong>after-tax average real price per pack of cigarettes</strong> (x) and <strong>the number of cigarette packs per capita sold</strong> (y). Since there is simultaneous causality between demand and supply, we need to use instrumental variable regression.</p>
<p>The The instrumental variable we are going to use for instrumenting the endogenous regressor is <em>SalesTax</em>, the portion of taxes on cigarettes arising from the general sales tax. The idea is that <em>SalesTax</em> is a relevant instrument as it is included in the after-tax average price per pack. Also, it is plausible that <em>SalesTax</em> is exogenous since the sales tax does not influence quantity sold directly but indirectly through the price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"CigarettesSW"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CigarettesSW)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     state      year         cpi          population           packs       
 AL     : 2   1985:48   Min.   :1.076   Min.   :  478447   Min.   : 49.27  
 AR     : 2   1995:48   1st Qu.:1.076   1st Qu.: 1622606   1st Qu.: 92.45  
 AZ     : 2             Median :1.300   Median : 3697472   Median :110.16  
 CA     : 2             Mean   :1.300   Mean   : 5168866   Mean   :109.18  
 CO     : 2             3rd Qu.:1.524   3rd Qu.: 5901500   3rd Qu.:123.52  
 CT     : 2             Max.   :1.524   Max.   :31493524   Max.   :197.99  
 (Other):84                                                                
     income               tax            price             taxs       
 Min.   :  6887097   Min.   :18.00   Min.   : 84.97   Min.   : 21.27  
 1st Qu.: 25520384   1st Qu.:31.00   1st Qu.:102.71   1st Qu.: 34.77  
 Median : 61661644   Median :37.00   Median :137.72   Median : 41.05  
 Mean   : 99878736   Mean   :42.68   Mean   :143.45   Mean   : 48.33  
 3rd Qu.:127313964   3rd Qu.:50.88   3rd Qu.:176.15   3rd Qu.: 59.48  
 Max.   :771470144   Max.   :99.00   Max.   :240.85   Max.   :112.63  
                                                                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute real per capita prices</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>rprice <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, price <span class="sc">/</span> cpi)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  compute the sales tax</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>salestax <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, (taxs <span class="sc">-</span> tax) <span class="sc">/</span> cpi)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a subset for the year 1995</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>c1995 <span class="ot">&lt;-</span> <span class="fu">subset</span>(CigarettesSW, year <span class="sc">==</span> <span class="st">"1995"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sls" class="level1">
<h1>2SLS</h1>
<section id="simple-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-regression-model">Simple regression model</h2>
<p>We first need to check if the independent variable (price) and the instrumental variable (sale tax) is correlated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(CigarettesSW<span class="sc">$</span>salestax, CigarettesSW<span class="sc">$</span>rprice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7035012</code></pre>
</div>
</div>
<p>Since x and z are highly correlated, we can move on to the 2SLS estimation.</p>
<p><strong>Step 1</strong>, <span class="math display">\[log(Price)=\delta_0+\delta_1Tax+v\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cig_s1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(rprice) <span class="sc">~</span> salestax, <span class="at">data =</span> c1995)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_s1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(rprice) ~ salestax, data = c1995)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.221027 -0.044324  0.000111  0.063730  0.210717 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.616546   0.029108   158.6  &lt; 2e-16 ***
salestax    0.030729   0.004802     6.4 7.27e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09394 on 46 degrees of freedom
Multiple R-squared:  0.471, Adjusted R-squared:  0.4595 
F-statistic: 40.96 on 1 and 46 DF,  p-value: 7.271e-08</code></pre>
</div>
</div>
<p><strong>Step 2</strong>, we estimate the fitted values obtained by the first stage regression</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lcigp_pred <span class="ot">&lt;-</span> cig_s1<span class="sc">$</span>fitted.values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Step 3</strong>, we run the second stage regression <span class="math display">\[log(packs)=\beta_0+\beta_1\hat{log_price}+\mu\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>cig_s2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(c1995<span class="sc">$</span>packs) <span class="sc">~</span> lcigp_pred)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_s2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(c1995$packs) ~ lcigp_pred)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.63180 -0.15802  0.00524  0.13574  0.61434 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   9.7199     1.8012   5.396  2.3e-06 ***
lcigp_pred   -1.0836     0.3766  -2.877  0.00607 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2264 on 46 degrees of freedom
Multiple R-squared:  0.1525,    Adjusted R-squared:  0.1341 
F-statistic: 8.277 on 1 and 46 DF,  p-value: 0.006069</code></pre>
</div>
</div>
<p>Now we have the model <span class="math display">\[log(pack)=9.72-1.08log(price)\]</span></p>
<p>Comparing the results of OLS regression, first, and second stage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cig_ols <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(packs) <span class="sc">~</span> <span class="fu">log</span>(rprice),<span class="at">data=</span>c1995)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(cig_ols,cig_s1,cig_s2,<span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==============================================================
                                    Dependent variable:       
                              --------------------------------
                              log(packs) log(rprice)  packs)  
                                 (1)         (2)        (3)   
--------------------------------------------------------------
log(rprice)                   -1.213***                       
                               (0.216)                        
                                                              
salestax                                  0.031***            
                                           (0.005)            
                                                              
lcigp_pred                                           -1.084***
                                                      (0.377) 
                                                              
Constant                      10.339***   4.617***   9.720*** 
                               (1.035)     (0.029)    (1.801) 
                                                              
--------------------------------------------------------------
Observations                      48         48         48    
R2                              0.406       0.471      0.152  
Adjusted R2                     0.393       0.459      0.134  
Residual Std. Error (df = 46)   0.190       0.094      0.226  
F Statistic (df = 1; 46)      31.409***   40.956***  8.277*** 
==============================================================
Note:                              *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Using OLS regression, a 1% increase in log(price) is associated with 1.21% decrease in log(pack). Using the 2SLS estimation, 1% increase in log(price) is associated with 1.08% decrease in log(pack), which is lower effect.</p>
<p>However, although 2SLS correctly estimates the coefficient, the standard error needs to be corrected. The function <code>ivreg()</code> from the package <code>AER</code> carries out 2SLS procedure automatically and generates the same coefficient and corrected standard error. Now we see the standard error of <em>log(rprice)</em> in 2SLS model (0.317) is higher than the standard error from the OLS regression (0.216). The 2SLS model also reports a lower level of significance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cig_ivreg <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(<span class="fu">log</span>(packs) <span class="sc">~</span> <span class="fu">log</span>(rprice) <span class="sc">|</span> salestax, <span class="at">data =</span> c1995)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_ivreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = log(packs) ~ log(rprice) | salestax, data = c1995)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.64619 -0.07732  0.02981  0.11283  0.41904 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   9.7199     1.5141   6.420 6.79e-08 ***
log(rprice)  -1.0836     0.3166  -3.422  0.00131 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1904 on 46 degrees of freedom
Multiple R-Squared: 0.4011, Adjusted R-squared: 0.3881 
Wald test: 11.71 on 1 and 46 DF,  p-value: 0.001313 </code></pre>
</div>
</div>
</section>
<section id="multiple-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-model">Multiple regression model</h2>
<p>After learning the simple regression, let’s add <em>income</em> as a control variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add rincome to the dataset</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>rincome <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, income <span class="sc">/</span> population <span class="sc">/</span> cpi)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>cigtax <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, tax<span class="sc">/</span>cpi)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>c1995 <span class="ot">&lt;-</span> <span class="fu">subset</span>(CigarettesSW, year <span class="sc">==</span> <span class="st">"1995"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We first estimate the model with one instrument (sales tax) and one control (income). In the function below, left of <code>|</code> shows the dependent variable <em>log(packs)</em>, the endogenous variable <em>log(rprice)</em>, and the exogenous variable, or control variable, <em>log(rincome)</em>. Right of the <code>|</code> shows the exogenous variable <em>log(rincome)</em> and instrumental variable <em>salestax</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>cig_ivreg2 <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(<span class="fu">log</span>(packs) <span class="sc">~</span> <span class="fu">log</span>(rprice) <span class="sc">+</span> <span class="fu">log</span>(rincome) <span class="sc">|</span> <span class="fu">log</span>(rincome) <span class="sc">+</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                    salestax, <span class="at">data =</span> c1995)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_ivreg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = log(packs) ~ log(rprice) + log(rincome) | log(rincome) + 
    salestax, data = c1995)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.611000 -0.086072  0.009423  0.106912  0.393159 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    9.4307     1.3584   6.943 1.24e-08 ***
log(rprice)   -1.1434     0.3595  -3.181  0.00266 ** 
log(rincome)   0.2145     0.2686   0.799  0.42867    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1896 on 45 degrees of freedom
Multiple R-Squared: 0.4189, Adjusted R-squared: 0.3931 
Wald test: 6.534 on 2 and 45 DF,  p-value: 0.003227 </code></pre>
</div>
</div>
<p>The estimated regression equation is <span class="math display">\[log(packs)=9.4307−1.1434log(rprice)+0.2145log(rincome)\]</span> A 1% increase in cigarette price is associated with a 1.14% decrease in cigarette sales. The impact is statisically significant at 1% level.</p>
<p>Now explore a model with one control (income) and two instruments (sales tax and cigtax). When the number of instruments exceeds the number of endogenous variables, the model is overidentified. This allows us to test the validity of the instruments using an overidentification test. More instruments can also help reduce standard errors in 2SLS, improving the statistical power of estimates.</p>
<p>Same as the previous model, left of the <code>|</code> shows the dependent variable, endogenous variable, and the control variable. Right of the <code>|</code> shows the control variable, and <strong>two</strong> instrumental variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>cig_ivreg3 <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(<span class="fu">log</span>(packs) <span class="sc">~</span> <span class="fu">log</span>(rprice) <span class="sc">+</span> <span class="fu">log</span>(rincome) <span class="sc">|</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">log</span>(rincome) <span class="sc">+</span> salestax <span class="sc">+</span> cigtax, <span class="at">data =</span> c1995)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_ivreg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = log(packs) ~ log(rprice) + log(rincome) | log(rincome) + 
    salestax + cigtax, data = c1995)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.6006931 -0.0862222 -0.0009999  0.1164699  0.3734227 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    9.8950     1.0586   9.348 4.12e-12 ***
log(rprice)   -1.2774     0.2632  -4.853 1.50e-05 ***
log(rincome)   0.2804     0.2386   1.175    0.246    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1879 on 45 degrees of freedom
Multiple R-Squared: 0.4294, Adjusted R-squared: 0.4041 
Wald test: 13.28 on 2 and 45 DF,  p-value: 2.931e-05 </code></pre>
</div>
</div>
<p>The estimated regression equation is <span class="math display">\[log(packs)=9.8950−1.2774log(rprice)+0.2804log(rincome)\]</span> A 1% increase in cigarette price is associated with a 1.28% decrease in cigarette sales. The effect is highly significant.</p>
</section>
</section>
<section id="accessing-instrumental-validity" class="level1">
<h1>Accessing Instrumental Validity</h1>
<section id="weak-instrument-test" class="level2">
<h2 class="anchored" data-anchor-id="weak-instrument-test">Weak instrument test</h2>
<p>To ensure the instruments (sales tax and cigarette tax) are strong predictors of the endogenous variable (log(rprice)), we perform a weak instrument test using the first-stage F-statistic.</p>
<p>Rule of thumb: If F &gt; 10, the instruments are strong; if F &lt; 10, they are weak, leading to biased IV estimates.</p>
</section>
<section id="overidentification-test-sargan-hansen" class="level2">
<h2 class="anchored" data-anchor-id="overidentification-test-sargan-hansen">Overidentification test (Sargan-Hansen)</h2>
<p>When there are more instruments than endogenous variables, the model is overidentified, allowing us to test whether the instruments are truly exogenous. The Sargan-Hansen J-test checks if the instruments are uncorrelated with the error term. A <strong>high</strong> p-value (&gt;0.05) suggests that the instruments are <strong>valid</strong>, while a low p-value indicates that at least one instrument may be invalid. This test helps ensure that our IV estimates are not biased due to instrument endogeneity.</p>
</section>
<section id="endogeneity-test-wu-hausman" class="level2">
<h2 class="anchored" data-anchor-id="endogeneity-test-wu-hausman">Endogeneity test (Wu-Hausman)</h2>
<p>The Wu-Hausman test checks whether an explanatory variable is endogenous, meaning it is correlated with the error term. If endogeneity is present, OLS estimates are biased and inconsistent, making IV estimation necessary. The test compares the results of OLS and IV regressions—if the two estimates significantly differ, it suggests that the endogenous variable should be instrumented. A low p-value (p &lt; 0.05) indicates that OLS is biased, confirming the need for IV, while a high p-value suggests that OLS may be sufficient. In R, this test can be performed using summary(iv_model, diagnostics = TRUE).</p>
<p>We can use one function to conduct all three tests:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_ivreg3,<span class="at">diagnostics =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = log(packs) ~ log(rprice) + log(rincome) | log(rincome) + 
    salestax + cigtax, data = c1995)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.6006931 -0.0862222 -0.0009999  0.1164699  0.3734227 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    9.8950     1.0586   9.348 4.12e-12 ***
log(rprice)   -1.2774     0.2632  -4.853 1.50e-05 ***
log(rincome)   0.2804     0.2386   1.175    0.246    

Diagnostic tests:
                 df1 df2 statistic p-value    
Weak instruments   2  44   244.734  &lt;2e-16 ***
Wu-Hausman         1  44     3.068  0.0868 .  
Sargan             1  NA     0.333  0.5641    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1879 on 45 degrees of freedom
Multiple R-Squared: 0.4294, Adjusted R-squared: 0.4041 
Wald test: 13.28 on 2 and 45 DF,  p-value: 2.931e-05 </code></pre>
</div>
</div>
<p>Results show that:</p>
<p>First, for weak instrument test, F&gt;10, confirming that sales tax and cigarette tax are strongly correelated with price. Weak instrument bias is not a concern.</p>
<p>Second, for endogeneity test, the null hypothesis is <em>log(rprice)</em> is exogenous, meaning we can use OLS model instead of instrumental variable. Since p&gt;0.05, we fail to reject the null hypothesis, meaning we have evidence for endogeneity and instrumental variable is preferred.</p>
<p>Finally, for overidentification test, the null hypothesis is the instruments are valid (uncorrelated with the error term). Since p&gt;0.05, we fail to reject the null hypothesis, meaning both sales tax and cigarette tax are likely valid instruments.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>