<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial_6 – DACSS790 Causal Inference Spring 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DACSS790 Causal Inference Spring 2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial1.html"> 
<span class="menu-text">Tutorial1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial2.html"> 
<span class="menu-text">Tutorial2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial3.html"> 
<span class="menu-text">Tutorial3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial4.html"> 
<span class="menu-text">Tutorial4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial5.html"> 
<span class="menu-text">Tutorial5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Tutorial6.html" aria-current="page"> 
<span class="menu-text">Tutorial6</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#front-end-matters" id="toc-front-end-matters" class="nav-link active" data-scroll-target="#front-end-matters">Front-end Matters</a></li>
  <li><a href="#the-structure-of-panel-data" id="toc-the-structure-of-panel-data" class="nav-link" data-scroll-target="#the-structure-of-panel-data">The structure of panel data</a></li>
  <li><a href="#fixed-effect" id="toc-fixed-effect" class="nav-link" data-scroll-target="#fixed-effect">Fixed Effect</a>
  <ul class="collapse">
  <li><a href="#textbook-example-data" id="toc-textbook-example-data" class="nav-link" data-scroll-target="#textbook-example-data">Textbook Example data</a></li>
  <li><a href="#ols-model" id="toc-ols-model" class="nav-link" data-scroll-target="#ols-model">OLS model</a></li>
  <li><a href="#ols-model-with-individual-as-control" id="toc-ols-model-with-individual-as-control" class="nav-link" data-scroll-target="#ols-model-with-individual-as-control">OLS model with ‘individual’ as control</a></li>
  <li><a href="#de-meaned-model" id="toc-de-meaned-model" class="nav-link" data-scroll-target="#de-meaned-model">De-meaned model</a></li>
  <li><a href="#fixed-effects" id="toc-fixed-effects" class="nav-link" data-scroll-target="#fixed-effects">Fixed effects</a></li>
  <li><a href="#clustered-standard-errors" id="toc-clustered-standard-errors" class="nav-link" data-scroll-target="#clustered-standard-errors">Clustered standard errors</a></li>
  <li><a href="#comparing-four-models" id="toc-comparing-four-models" class="nav-link" data-scroll-target="#comparing-four-models">Comparing four models</a></li>
  </ul></li>
  <li><a href="#two-way-fixed-effect" id="toc-two-way-fixed-effect" class="nav-link" data-scroll-target="#two-way-fixed-effect">Two-way Fixed Effect</a>
  <ul class="collapse">
  <li><a href="#practice-twfe" id="toc-practice-twfe" class="nav-link" data-scroll-target="#practice-twfe">Practice TWFE</a></li>
  <li><a href="#clustered-standard-error" id="toc-clustered-standard-error" class="nav-link" data-scroll-target="#clustered-standard-error">Clustered standard error</a></li>
  </ul></li>
  <li><a href="#random-effect" id="toc-random-effect" class="nav-link" data-scroll-target="#random-effect">Random Effect</a>
  <ul class="collapse">
  <li><a href="#hausman-test-should-we-trust-random-effects" id="toc-hausman-test-should-we-trust-random-effects" class="nav-link" data-scroll-target="#hausman-test-should-we-trust-random-effects">Hausman Test: Should We Trust Random Effects?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 6 Panel Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Panel data analysis is a powerful tool in causal inference, enabling researchers to control for unobserved, time-invariant confounding and analyze changes within units over time. This tutorial will guide you through key panel data methods in R, from data preparation to advanced causal modeling. We will use tidyverse tools to reshape and explore panel data, and estimate fixed effects, random effects, and nonlinear models. We’ll also explore how to extend these models to include mediation analysis and instrumental variables within a panel framework.</p>
<p>By the end of this tutorial, you will be familiar with:</p>
<p>1 .&nbsp;The structure of panel data</p>
<p>2 .&nbsp;Estimating fixed and random effects models</p>
<p>3 .&nbsp;Models with nonlinear outcomes</p>
<p>4 .&nbsp;Incorporating mediation and instrumental variable approaches in panel data</p>
<section id="front-end-matters" class="level1">
<h1>Front-end Matters</h1>
<p>We use <code>fixest</code> package for fixed effect model. For random effect, we also use the <code>plm</code> package. For mediation analysis and instrumental variable in panel data, we’ll use a combination of <code>fixest</code> and the packages we introduced earlier: <code>mediation</code> and <code>AER</code>.</p>
<p>The <code>fixest</code> package is a powerful and efficient tool for estimating fixed effects models in R. It supports multi-way fixed effects (e.g., individual and time), clustered standard errors, and instrumental variable estimation — all with a clean and flexible syntax. It’s well-suited for large datasets and is increasingly popular in applied causal inference research.</p>
<p>The <code>plm</code> package is a classic package for panel data analysis in R. It provides a consistent interface for estimating fixed effects, random effects, and other panel-specific models like first differences and between estimators. While it’s less flexible than <code>fixest</code>, it remains a useful tool for learning core panel data methods and comparing estimation strategies like fixed vs.&nbsp;random effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: 

 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.
 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS

Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select

Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loading required package: mvtnorm
Loading required package: sandwich
mediation: Causal Mediation Analysis
Version: 4.5.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

Loading required package: lmtest
Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric

Loading required package: survival</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("fixest")</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("plm")</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plm'

The following objects are masked from 'package:dplyr':

    between, lag, lead</code></pre>
</div>
</div>
</section>
<section id="the-structure-of-panel-data" class="level1">
<h1>The structure of panel data</h1>
<p>Panel data consists of observations on multiple units (such as individuals, countries, or firms) tracked over multiple time periods. It involves observing the same units across time, although not every unit needs to appear in every time period — this is known as an unbalanced panel. Each row represents a unit at a specific time point, forming a long-format structure. This setup enables researchers to study within-unit change over time while controlling for time-invariant characteristics. By combining both cross-sectional and time-series dimensions, panel data offers powerful opportunities for causal inference.</p>
<p>This is an example of long-format panel data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tidydata <span class="ot">&lt;-</span> table1</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tidydata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  country      year  cases population
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 Afghanistan  1999    745   19987071
2 Afghanistan  2000   2666   20595360
3 Brazil       1999  37737  172006362
4 Brazil       2000  80488  174504898
5 China        1999 212258 1272915272
6 China        2000 213766 1280428583</code></pre>
</div>
</div>
<p>But sometimes, when we receive data, it doesn’t come in the long format required for panel data analysis. Instead, it may be in a wide format, where repeated measurements for each unit (e.g., different years) appear as separate columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>untidydata <span class="ot">&lt;-</span> table4a</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>untidydata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  country     `1999` `2000`
  &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1 Afghanistan    745   2666
2 Brazil       37737  80488
3 China       212258 213766</code></pre>
</div>
</div>
<p>We’ll need to reshape this data into long format using <code>pivot_longer()</code> before we can analyze it as panel data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>longer <span class="ot">&lt;-</span> untidydata <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(<span class="st">`</span><span class="at">1999</span><span class="st">`</span>, <span class="st">`</span><span class="at">2000</span><span class="st">`</span>), <span class="at">names_to =</span> <span class="st">"year"</span>, <span class="at">values_to =</span> <span class="st">"cases"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#specifying the columns by column names</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>longer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  country     year   cases
  &lt;chr&gt;       &lt;chr&gt;  &lt;dbl&gt;
1 Afghanistan 1999     745
2 Afghanistan 2000    2666
3 Brazil      1999   37737
4 Brazil      2000   80488
5 China       1999  212258
6 China       2000  213766</code></pre>
</div>
</div>
</section>
<section id="fixed-effect" class="level1">
<h1>Fixed Effect</h1>
<section id="textbook-example-data" class="level2">
<h2 class="anchored" data-anchor-id="textbook-example-data">Textbook Example data</h2>
<p>This example dataset simulates a scenario where we observe multiple individuals over time and want to study the relationship between Intensity of Reminders (e.g., how often someone is nudged to eat healthy) and their Healthy Eating Score. The data includes four individuals, each observed eight times, with individual differences in both baseline behavior and response to reminders. This structure mimics panel data, where repeated observations are collected for the same units.</p>
<p>The code below generates this data, ensuring some variation in reminder intensity and healthy eating behavior across individuals and time. We’ll use this dataset to illustrate how different modeling strategies — including OLS, fixed effects, and demeaning — handle within- and between-individual variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2000</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>Demo <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Individual =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">'You'</span>,<span class="dv">8</span>),<span class="fu">rep</span>(<span class="st">'Me'</span>,<span class="dv">8</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">rep</span>(<span class="st">'Shamma'</span>,<span class="dv">8</span>),<span class="fu">rep</span>(<span class="st">'Liqing'</span>,<span class="dv">8</span>)),<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Me'</span>,<span class="st">'You'</span>,<span class="st">'Liqing'</span>,<span class="st">'Shamma'</span>)),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">IndNo =</span> <span class="fu">sort</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">8</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">IntensityOfReminders =</span> <span class="fu">runif</span>(<span class="dv">32</span>)<span class="sc">*</span><span class="dv">5</span> <span class="sc">+</span> IndNo) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HealthyEatingScore =</span> <span class="fu">runif</span>(<span class="dv">32</span>)<span class="sc">*</span><span class="dv">10</span> <span class="sc">+</span> IntensityOfReminders <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>IndNo) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HealthyEatingScore =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    HealthyEatingScore <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> HealthyEatingScore))</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Demo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Individual IndNo IntensityOfReminders HealthyEatingScore
  &lt;fct&gt;      &lt;int&gt;                &lt;dbl&gt;              &lt;dbl&gt;
1 You            1                 1.98               1.20
2 You            1                 4.58              11.7 
3 You            1                 2.81               6.57
4 You            1                 2.96               7.26
5 You            1                 5.07               4.28
6 You            1                 3.14              10.9 </code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Demo, <span class="fu">aes</span>(<span class="at">x =</span> IntensityOfReminders,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">y =</span> HealthyEatingScore, </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> Individual)) <span class="sc">+</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_pubr</span>() <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Intensity of Reminders"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Healthy Eating Score"</span>)<span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text         =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">family=</span><span class="st">"Garamond"</span>),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">family=</span><span class="st">"Garamond"</span>),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">family=</span> <span class="st">"Garamond"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial6_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ols-model" class="level2">
<h2 class="anchored" data-anchor-id="ols-model">OLS model</h2>
<p>We begin with a simple Ordinary Least Squares (OLS) regression, where we estimate the relationship between Intensity of Reminders and Healthy Eating Score, ignoring individual differences. This model assumes that all individuals share the same intercept and slope — that is, it pools all observations together without accounting for the fact that each individual may have a different baseline level of healthy eating. While easy to estimate and interpret, this approach risks omitted variable bias if there are time-invariant individual characteristics (like personal motivation or lifestyle) that influence both the reminders and the outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HealthyEatingScore<span class="sc">~</span>IntensityOfReminders, <span class="at">data=</span>Demo)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HealthyEatingScore ~ IntensityOfReminders, data = Demo)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7976 -2.8402  0.0088  2.0486  7.0025 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)            3.8820     1.6860   2.303   0.0284 *
IntensityOfReminders   0.1850     0.3004   0.616   0.5427  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.311 on 30 degrees of freedom
Multiple R-squared:  0.01248,   Adjusted R-squared:  -0.02044 
F-statistic: 0.3791 on 1 and 30 DF,  p-value: 0.5427</code></pre>
</div>
</div>
<p><span class="math inline">\(y = 0.185X+3.882\)</span>. This indicates that for each one-unit increase in reminder intensity, the Healthy Eating Score increases by 0.19 points. However, the p-value for this effect is 0.543, which indicates that the relationship is not statistically significant at conventional levels.</p>
</section>
<section id="ols-model-with-individual-as-control" class="level2">
<h2 class="anchored" data-anchor-id="ols-model-with-individual-as-control">OLS model with ‘individual’ as control</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HealthyEatingScore <span class="sc">~</span> IntensityOfReminders <span class="sc">+</span> Individual, <span class="at">data =</span> Demo)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HealthyEatingScore ~ IntensityOfReminders + Individual, 
    data = Demo)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3688 -2.2382 -0.0088  1.6162  4.6900 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)            0.7580     1.8078   0.419   0.6783  
IntensityOfReminders   0.7448     0.3676   2.026   0.0527 .
IndividualYou          3.3317     1.4802   2.251   0.0327 *
IndividualLiqing      -2.2873     1.7970  -1.273   0.2139  
IndividualShamma      -0.3349     1.7174  -0.195   0.8469  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.959 on 27 degrees of freedom
Multiple R-squared:  0.2902,    Adjusted R-squared:  0.1851 
F-statistic:  2.76 on 4 and 27 DF,  p-value: 0.04808</code></pre>
</div>
</div>
<p>In the output, there’s a coefficient for each group, and ‘Me’ is treated as the baseline. The slope for Intensity of Reminders is now estimated at 0.74, meaning that for a one-unit increase in reminder intensity, the Healthy Eating Score increases by 0.74 points on average. The p-value is now 0.052. The intercept (0.76) represents the expected Healthy Eating Score for the reference individual (‘Me’) when Intensity of Reminders is 0. ‘You’ tends to score 3.33 points higher than Me (significant). ‘Liqing’ scores 2.29 points lower, but this is not statistically significant.</p>
<p>We can also visualize the results of this model to reinforce the logic. The plot below shows that each individual has their own intercept, while sharing the same slope for ‘Intensity of Reminders’. This aligns with the fixed effects idea: we allow each person to start from a different baseline, but we assume the effect of reminders is consistent across individuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predicted values for each observation</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Demo <span class="ot">&lt;-</span> Demo <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fitted =</span> <span class="fu">predict</span>(model2))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot: Individual lines with shared slope, different intercepts</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Demo, <span class="fu">aes</span>(<span class="at">x =</span> IntensityOfReminders, <span class="at">y =</span> HealthyEatingScore, <span class="at">color =</span> Individual)) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Fitted), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fixed Effects Logic: Common Slope, Varying Intercepts"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Intensity of Reminders"</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Healthy Eating Score"</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">"Garamond"</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial6_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="de-meaned-model" class="level2">
<h2 class="anchored" data-anchor-id="de-meaned-model">De-meaned model</h2>
<p>Another way to estimate a fixed effects model is by manually demeaning the data — that is, subtracting each individual’s mean from their own observations. This removes all between-individual variation, leaving only the within-individual variation over time. When we run a regression on the demeaned variables, we get the same slope as a fixed effects model, since we’ve effectively controlled for all time-invariant individual characteristics.</p>
<p>This approach is useful for illustrating the logic of fixed effects and helps students see exactly what is being removed from the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>Demo_demeaned <span class="ot">&lt;-</span> Demo <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Individual) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y_demeaned =</span> HealthyEatingScore <span class="sc">-</span> <span class="fu">mean</span>(HealthyEatingScore),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">X_demeaned =</span> IntensityOfReminders <span class="sc">-</span> <span class="fu">mean</span>(IntensityOfReminders)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the model</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y_demeaned <span class="sc">~</span> X_demeaned, <span class="at">data =</span> Demo_demeaned)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y_demeaned ~ X_demeaned, data = Demo_demeaned)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3688 -2.2382 -0.0088  1.6162  4.6900 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 2.739e-16  4.962e-01   0.000    1.000  
X_demeaned  7.448e-01  3.487e-01   2.136    0.041 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.807 on 30 degrees of freedom
Multiple R-squared:  0.132, Adjusted R-squared:  0.103 
F-statistic: 4.561 on 1 and 30 DF,  p-value: 0.04098</code></pre>
</div>
</div>
<p>Same as model2, the slope for Intensity of Reminders is still 0.74, meaning that for a one-unit increase in reminder intensity, the Healthy Eating Score increases by 0.74 points on average. This confirms that demeaning preserves the within-unit effect. The p-value is now 0.041, indicating a statistically significant positive relationship at the 5% level.</p>
<p>The intercept is essentially zero and not significant — this is expected. Since we’ve demeaned both the outcome and the predictor, the mean of each is zero by construction. That’s why the intercept is near zero and meaningless in this context.</p>
</section>
<section id="fixed-effects" class="level2">
<h2 class="anchored" data-anchor-id="fixed-effects">Fixed effects</h2>
<p>The most efficient and flexible way to estimate a fixed effects model in R is by using the <code>fixest</code> package. This package allows us to easily specify fixed effects using the <code>|</code> operator, without manually creating dummy variables or demeaning the data. Here, we include Individual as a fixed effect to account for time-invariant differences across individuals, while estimating a common slope for ‘IntensityOfReminders’.</p>
<p>This approach is mathematically equivalent to both the OLS with individual dummies and the demeaned model. However, fixest handles fixed effects more efficiently and also supports clustered standard errors, multi-way fixed effects, and IV estimation — making it a preferred choice for applied panel data analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(HealthyEatingScore <span class="sc">~</span> IntensityOfReminders <span class="sc">|</span> Individual, <span class="at">data =</span> Demo)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: HealthyEatingScore
Observations: 32
Fixed-effects: Individual: 4
Standard-errors: Clustered (Individual) 
                     Estimate Std. Error t value Pr(&gt;|t|) 
IntensityOfReminders 0.744796    0.47583 1.56526  0.21549 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.71763     Adj. R2: 0.185071
                Within R2: 0.131979</code></pre>
</div>
</div>
<p>The output indicates that we have 32 observations within 4 groups. The standard error is clustered, which is the default of <code>feols</code> function.</p>
</section>
<section id="clustered-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="clustered-standard-errors">Clustered standard errors</h2>
<p><strong>Clustered standard errors</strong> adjust for the fact that observations within the same group (or “cluster”) — such as individuals in panel data — may not be independent of one another. In panel data, for example, repeated measurements from the same person are likely correlated. If we ignore this and treat all observations as independent, our standard errors may be too small, leading to overstated statistical significance. Clustered standard errors correct for this by allowing for arbitrary correlation of errors within each cluster, making our inference (like p-values and confidence intervals) more reliable.</p>
<p>We can get heteroskedasticity-robust standard errors using this function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4, <span class="at">vcov =</span> <span class="st">"hetero"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: HealthyEatingScore
Observations: 32
Fixed-effects: Individual: 4
Standard-errors: Heteroskedasticity-robust 
                     Estimate Std. Error t value Pr(&gt;|t|)    
IntensityOfReminders 0.744796   0.392933 1.89548 0.068782 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.71763     Adj. R2: 0.185071
                Within R2: 0.131979</code></pre>
</div>
</div>
<p>We see that for the model with clustered standard error, the p-value is 0.22, meaning that the effect is not statistically significant at conventional levels in this specification. But for the model with heteroskedasticity-robust standard errors, the p-value is 0.07, which supports what we said earlier: If we ignore this and treat all observations as independent, our standard errors may be too small, leading to overstated statistical significance.</p>
<p>You may also notice there is no ‘intercept’ in the model output of the fixed effects model. This is because fixed effects absorb the intercepts by estimating a separate intercept for each individual. Instead of reporting a single overall intercept, the model includes individual-specific fixed effects that capture each person’s baseline level of the outcome.</p>
<p>You can view these estimated individual intercepts using the <code>fixef()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Individual
    Liqing         Me     Shamma        You 
-1.5292183  0.7580456  0.4231911  4.0897559 

attr(,"class")
[1] "fixest.fixef" "list"        
attr(,"exponential")
[1] FALSE</code></pre>
</div>
</div>
</section>
<section id="comparing-four-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-four-models">Comparing four models</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, model2, model3, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Comparison of OLS, Individual Controls, Demeaned, and Fixed Effects Models"</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"OLS"</span>, <span class="st">"OLS + Individual"</span>, <span class="st">"Demeaned"</span>, <span class="st">"Fixed Effects"</span>),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">dep.var.labels =</span> <span class="st">"Healthy Eating Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Comparison of OLS, Individual Controls, Demeaned, and Fixed Effects Models
=================================================================================
                                         Dependent variable:                     
                     ------------------------------------------------------------
                              Healthy Eating Score                Y_demeaned     
                            OLS           OLS + Individual         Demeaned      
                            (1)                 (2)                  (3)         
---------------------------------------------------------------------------------
IntensityOfReminders       0.185               0.745*                            
                          (0.300)             (0.368)                            
                                                                                 
IndividualYou                                 3.332**                            
                                              (1.480)                            
                                                                                 
IndividualLiqing                               -2.287                            
                                              (1.797)                            
                                                                                 
IndividualShamma                               -0.335                            
                                              (1.717)                            
                                                                                 
X_demeaned                                                         0.745**       
                                                                   (0.349)       
                                                                                 
Constant                  3.882**              0.758                0.000        
                          (1.686)             (1.808)              (0.496)       
                                                                                 
---------------------------------------------------------------------------------
Observations                 32                  32                   32         
R2                         0.012               0.290                0.132        
Adjusted R2                -0.020              0.185                0.103        
Residual Std. Error   3.311 (df = 30)     2.959 (df = 27)      2.807 (df = 30)   
F Statistic          0.379 (df = 1; 30) 2.760** (df = 4; 27) 4.561** (df = 1; 30)
=================================================================================
Note:                                                 *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>The logic is the same across model2, model3 and model4, and they all give you the same slope — but small differences in how the model handles variation and estimates standard errors can lead to slightly different p-values. In practice, we usually rely on packages like <code>fixest</code> for efficiency and robust SEs.</p>
</section>
</section>
<section id="two-way-fixed-effect" class="level1">
<h1>Two-way Fixed Effect</h1>
<p>In the previous sections, we used fixed effects to control for unobserved, time-invariant differences between individuals — such as personality, baseline health, or preferences. However, in many panel data settings, there may also be time-specific shocks that affect all individuals in the same period, such as policy changes, economic shifts, or public health campaigns. Two-way fixed effects (TWFE) models address this by adding both individual and time fixed effects, allowing us to control for who someone is and when the observation occurred. This helps isolate the effect of a treatment or variable of interest by removing bias from both stable individual characteristics and shared time shocks.</p>
<p>For demonstration purposes, we add a simple fake time variable to our dataset, assuming each individual is observed across eight time periods. This allows us to simulate a panel structure with both individual and time dimensions. We then estimate two models: a standard fixed effects model with only individual fixed effects (model_fe), and a two-way fixed effects model that includes both individual and time fixed effects (model_twfe). The two-way model controls not only for each person’s baseline behavior but also for any year-specific effects that may influence the outcome. This is particularly useful when we suspect that external events — such as national trends or policy shifts — may impact all individuals during the same period.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add fake time variable for demo</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2000</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>Demo<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">times =</span> <span class="dv">4</span>)  <span class="co"># assuming 8 time points</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit both models</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>model_fe   <span class="ot">&lt;-</span> <span class="fu">feols</span>(HealthyEatingScore <span class="sc">~</span> IntensityOfReminders <span class="sc">|</span> Individual, <span class="at">data =</span> Demo)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>model_twfe <span class="ot">&lt;-</span> <span class="fu">feols</span>(HealthyEatingScore <span class="sc">~</span> IntensityOfReminders <span class="sc">|</span> Individual <span class="sc">+</span> Time, <span class="at">data =</span> Demo)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_fe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: HealthyEatingScore
Observations: 32
Fixed-effects: Individual: 4
Standard-errors: Clustered (Individual) 
                     Estimate Std. Error t value Pr(&gt;|t|) 
IntensityOfReminders 0.744796    0.47583 1.56526  0.21549 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.71763     Adj. R2: 0.185071
                Within R2: 0.131979</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_twfe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: HealthyEatingScore
Observations: 32
Fixed-effects: Individual: 4,  Time: 8
Standard-errors: Clustered (Individual) 
                     Estimate Std. Error t value Pr(&gt;|t|)    
IntensityOfReminders 0.907467   0.378913 2.39492 0.096313 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.37174     Adj. R2: 0.162072
                Within R2: 0.1712  </code></pre>
</div>
</div>
<p>In the two-way fixed effects (TWFE) model, the estimated effect of ‘IntensityOfReminders’ on ‘HealthyEatingScore’ is 0.91, compared to 0.74 in the standard fixed effects (FE) model. This suggests that, after controlling for both individual characteristics and common time effects, the effect of reminder intensity is stronger than what the one-way FE model estimated.</p>
<p>The p-value for the TWFE model is 0.096, indicating the effect is marginally significant at the 10% level, while the FE model’s p-value was higher (0.215), suggesting non-significance. This shift implies that time fixed effects may have reduced noise or bias in the original model — potentially caused by unobserved events affecting all individuals in a given time period.</p>
<p>Additionally, the RMSE (root mean squared error) decreased from 2.72 (FE) to 2.37 (TWFE), indicating a better model fit with the inclusion of time fixed effects.</p>
<section id="practice-twfe" class="level2">
<h2 class="anchored" data-anchor-id="practice-twfe">Practice TWFE</h2>
<p>Now, let’s have a practice using real cross-country time series data: the gapminder dataset. This dataset includes information on life expectancy, GDP per capita, and population size for countries around the world from 1952 to 2007, in five-year increments. It provides a simple but effective example of panel data where each country is observed repeatedly over time. We’ll use this dataset to estimate a two-way fixed effects model, controlling for both country-specific characteristics (like geography, health infrastructure, or culture) and time-specific shocks (like global medical advances or economic downturns).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename for consistency</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">country =</span> country, <span class="at">year =</span> year,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">life_exp =</span> lifeExp,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">gdp_pc =</span> gdpPercap) <span class="sc">%&gt;%</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_pop =</span> <span class="fu">log</span>(pop))</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  country     continent  year life_exp      pop gdp_pc log_pop
  &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;    &lt;dbl&gt;    &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 Afghanistan Asia       1952     28.8  8425333   779.    15.9
2 Afghanistan Asia       1957     30.3  9240934   821.    16.0
3 Afghanistan Asia       1962     32.0 10267083   853.    16.1
4 Afghanistan Asia       1967     34.0 11537966   836.    16.3
5 Afghanistan Asia       1972     36.1 13079460   740.    16.4
6 Afghanistan Asia       1977     38.4 14880372   786.    16.5</code></pre>
</div>
</div>
<p>Our outcome of interest will be life expectancy, and we’ll examine how it is associated with GDP per capita, while controlling for population size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>model_gap_FE <span class="ot">&lt;-</span> <span class="fu">feols</span>(life_exp <span class="sc">~</span> <span class="fu">log</span>(gdp_pc) <span class="sc">+</span> log_pop <span class="sc">|</span> country, <span class="at">data =</span> df)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>model_gap_TWFE <span class="ot">&lt;-</span> <span class="fu">feols</span>(life_exp <span class="sc">~</span> <span class="fu">log</span>(gdp_pc) <span class="sc">+</span> log_pop <span class="sc">|</span> country <span class="sc">+</span> year, <span class="at">data =</span> df)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gap_FE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: life_exp
Observations: 1,704
Fixed-effects: country: 142
Standard-errors: Clustered (country) 
            Estimate Std. Error  t value   Pr(&gt;|t|)    
log(gdp_pc)  4.47740   0.555508  8.06001 2.9408e-13 ***
log_pop     11.95839   0.664803 17.98789  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 3.09349     Adj. R2: 0.937351
                Within R2: 0.779557</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gap_TWFE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: life_exp
Observations: 1,704
Fixed-effects: country: 142,  year: 12
Standard-errors: Clustered (country) 
            Estimate Std. Error t value   Pr(&gt;|t|)    
log(gdp_pc)  2.98160   0.765053 3.89725 1.4984e-04 ***
log_pop      8.32135   1.050069 7.92458 6.2636e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.96801     Adj. R2: 0.941921
                Within R2: 0.189886</code></pre>
</div>
</div>
<p>Let’s compare the results from the one-way fixed effects model (country only) and the two-way fixed effects model (country and year).</p>
<p>In the one-way fixed effects model, the estimated effect of <em>log(gdp_pc)</em> on <em>life expectancy</em> is 4.48, while in the two-way fixed effects model, the estimate drops to 2.98. Similarly, the effect of <em>log_pop</em> decreases from 11.96 to 8.32. These differences suggest that once we control for year-specific shocks – such as global medical advances, international development programs, or major world events – the explanatory power of GDP and population size becomes more conservative. That is, GDP still has a positive association with life expectancy, but the effect is smaller once we account for trends that influence all countries in a given year.</p>
<p>We also see changes in model fit statistics. The RMSE (Root Mean Squared Error), which tells us the average prediction error in the units of life expectancy, drops slightly from 3.09 to 2.97, indicating that the two-way fixed effects model makes slightly more accurate predictions overall. However, the within R² decreases dramatically from 0.78 to 0.19. This may seem surprising, but it’s expected. When we include year fixed effects, we absorb more variation from the outcome variable (life expectancy), leaving less variation for GDP and population to explain. That doesn’t mean the model is worse – it just means that more confounding variation has been removed.</p>
</section>
<section id="clustered-standard-error" class="level2">
<h2 class="anchored" data-anchor-id="clustered-standard-error">Clustered standard error</h2>
<p>By default, when we fit a fixed effects model using <code>feols()</code> with multiple fixed effects (e.g., country + year), the standard errors are clustered by the first fixed effect – in this case, country. This makes sense, as we usually want to account for serial correlation within each unit over time.</p>
<p>If you want to change the clustering variable, you can explicitly specify it using the cluster argument directly in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model_twfe_clustered <span class="ot">&lt;-</span> <span class="fu">feols</span>(life_exp <span class="sc">~</span> <span class="fu">log</span>(gdp_pc) <span class="sc">+</span> log_pop <span class="sc">|</span> country <span class="sc">+</span> year, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">cluster =</span> <span class="sc">~</span>year,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> df)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_twfe_clustered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: life_exp
Observations: 1,704
Fixed-effects: country: 142,  year: 12
Standard-errors: Clustered (year) 
            Estimate Std. Error t value   Pr(&gt;|t|)    
log(gdp_pc)  2.98160   0.117151 25.4509 3.9736e-11 ***
log_pop      8.32135   0.609468 13.6535 3.0544e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.96801     Adj. R2: 0.941921
                Within R2: 0.189886</code></pre>
</div>
</div>
<p>In the example above, we clustered standard errors by year, which allows for arbitrary correlation of errors across countries within the same year. This is useful for demonstration purposes to show how clustering affects inference. However, in practice, especially when working with panel data, it is more common to cluster by the unit of observation – in this case, country – because observations within the same country over time are likely to be correlated. Clustering by country accounts for serial correlation in the residuals and typically produces more conservative standard errors, which helps ensure valid statistical inference.</p>
</section>
</section>
<section id="random-effect" class="level1">
<h1>Random Effect</h1>
<p>The random effects model is an alternative to fixed effects for analyzing panel data. While fixed effects estimate a separate intercept for each unit (e.g., each country), random effects assume that these unit-specific differences are random deviations from a shared average intercept, drawn from a common distribution. This assumption allows random effects models to use both within-unit and between-unit variation, which often makes them more efficient. However, this efficiency comes at a cost: it assumes that the unit-level effects are not correlated with the explanatory variables. If that assumption is violated, the random effects model may produce biased estimates. We’ll demonstrate this using the <code>gapminder</code> data, then test the assumptions using the Hausman test.</p>
<p>We’ll use the <code>plm</code> package to estimate both fixed and random effects models for life expectancy using GDP per capita and population as predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data as panel</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>pdata <span class="ot">&lt;-</span> <span class="fu">pdata.frame</span>(gapminder, <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"year"</span>))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed effects (country + year)</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>fe_model <span class="ot">&lt;-</span> <span class="fu">plm</span>(lifeExp <span class="sc">~</span> <span class="fu">log</span>(gdpPercap) <span class="sc">+</span> <span class="fu">log</span>(pop), <span class="at">data =</span> pdata, <span class="at">model =</span> <span class="st">"within"</span>, <span class="at">effect =</span> <span class="st">"twoways"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Random effects</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>re_model <span class="ot">&lt;-</span> <span class="fu">plm</span>(lifeExp <span class="sc">~</span> <span class="fu">log</span>(gdpPercap) <span class="sc">+</span> <span class="fu">log</span>(pop), <span class="at">data =</span> pdata, <span class="at">model =</span> <span class="st">"random"</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare results</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fe_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Twoways effects Within Model

Call:
plm(formula = lifeExp ~ log(gdpPercap) + log(pop), data = pdata, 
    effect = "twoways", model = "within")

Balanced Panel: n = 142, T = 12, N = 1704

Residuals:
      Min.    1st Qu.     Median    3rd Qu.       Max. 
-23.592495  -1.336179   0.053776   1.688032   8.811396 

Coefficients:
               Estimate Std. Error t-value  Pr(&gt;|t|)    
log(gdpPercap)  2.98160    0.25747  11.580 &lt; 2.2e-16 ***
log(pop)        8.32135    0.45980  18.098 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    18529
Residual Sum of Squares: 15011
R-Squared:      0.18989
Adj. R-Squared: 0.10934
F-statistic: 181.538 on 2 and 1549 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(re_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Random Effect Model 
   (Swamy-Arora's transformation)

Call:
plm(formula = lifeExp ~ log(gdpPercap) + log(pop), data = pdata, 
    model = "random")

Balanced Panel: n = 142, T = 12, N = 1704

Effects:
                 var std.dev share
idiosyncratic 10.453   3.233 0.256
individual    30.392   5.513 0.744
theta: 0.8331

Residuals:
      Min.    1st Qu.     Median    3rd Qu.       Max. 
-22.337727  -2.386962   0.040912   2.663395  12.373829 

Coefficients:
                 Estimate Std. Error z-value  Pr(&gt;|z|)    
(Intercept)    -115.17778    3.35470 -34.333 &lt; 2.2e-16 ***
log(gdpPercap)    6.71888    0.21960  30.596 &lt; 2.2e-16 ***
log(pop)          7.60075    0.22363  33.987 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    79829
Residual Sum of Squares: 26968
R-Squared:      0.66217
Adj. R-Squared: 0.66178
Chisq: 3334.13 on 2 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
</div>
<p>From the random effect output, we see that, 74% of the total error variance is due to differences between countries, and 26% is due to variation within countries over time. Unlike the fixed effects model, the random effects model includes an additional line in the output for the intercept: -115.18. This is the grand mean intercept, representing the average baseline level of the outcome across all units before adding unit-specific random deviations. In contrast, fixed effects models don’t estimate a common intercept because each unit has its own.</p>
<section id="hausman-test-should-we-trust-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="hausman-test-should-we-trust-random-effects">Hausman Test: Should We Trust Random Effects?</h2>
<p>The Hausman test allows us to formally test whether the random effects model is appropriate. The null hypothesis is that the random effects model is consistent — in other words, that there is no correlation between the unit effects and the regressors. If the test rejects the null, we should use fixed effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hausman test</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>hausman_result <span class="ot">&lt;-</span> <span class="fu">phtest</span>(fe_model, re_model)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>hausman_result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hausman Test

data:  lifeExp ~ log(gdpPercap) + log(pop)
chisq = 7075.6, df = 2, p-value &lt; 2.2e-16
alternative hypothesis: one model is inconsistent</code></pre>
</div>
</div>
<p>p-value is smaller than 0.05, so we reject the null , and should use fixed effects (random effects are likely biased). This test helps you decide between fixed and random effects not based on fit alone, but based on the core assumption about unobserved heterogeneity in your panel data.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>