<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial_4 – DACSS790 Causal Inference Spring 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DACSS790 Causal Inference Spring 2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial1.html"> 
<span class="menu-text">Tutorial1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial2.html"> 
<span class="menu-text">Tutorial2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Tutorial3.html"> 
<span class="menu-text">Tutorial3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Tutorial4.html" aria-current="page"> 
<span class="menu-text">Tutorial4</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#front-end-matters" id="toc-front-end-matters" class="nav-link active" data-scroll-target="#front-end-matters">Front-end Matters</a></li>
  <li><a href="#traditional-mediation-analysis" id="toc-traditional-mediation-analysis" class="nav-link" data-scroll-target="#traditional-mediation-analysis">Traditional mediation analysis</a></li>
  <li><a href="#causal-mediation-analysis" id="toc-causal-mediation-analysis" class="nav-link" data-scroll-target="#causal-mediation-analysis">Causal mediation analysis</a>
  <ul class="collapse">
  <li><a href="#simple-model" id="toc-simple-model" class="nav-link" data-scroll-target="#simple-model">Simple model</a></li>
  <li><a href="#model-with-covariates" id="toc-model-with-covariates" class="nav-link" data-scroll-target="#model-with-covariates">Model with covariates</a></li>
  <li><a href="#sensitivity" id="toc-sensitivity" class="nav-link" data-scroll-target="#sensitivity">Sensitivity</a></li>
  <li><a href="#mediator-is-also-moderator" id="toc-mediator-is-also-moderator" class="nav-link" data-scroll-target="#mediator-is-also-moderator">Mediator is also moderator</a></li>
  </ul></li>
  <li><a href="#structural-equation-modeling-sem" id="toc-structural-equation-modeling-sem" class="nav-link" data-scroll-target="#structural-equation-modeling-sem">Structural Equation Modeling (SEM)</a>
  <ul class="collapse">
  <li><a href="#parallel-mediation" id="toc-parallel-mediation" class="nav-link" data-scroll-target="#parallel-mediation">Parallel mediation</a></li>
  <li><a href="#sequential-mediation" id="toc-sequential-mediation" class="nav-link" data-scroll-target="#sequential-mediation">Sequential mediation</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 4 Mediation Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Mediation analysis is a key tool in causal inference, helping researchers understand how and why a treatment influences an outcome through an intermediate variable (mediator). In this tutorial, you’ll learn how to implement both <strong>traditional and causal mediation analysis</strong> in R using the <code>mediation</code> package, as well as explore <strong>structural equation modeling (SEM)</strong> with the <code>lavaan</code> package. By the end of this tutorial, you should be familiar with the following:</p>
<p>1.&nbsp;packages <code>mediation</code> and <code>lavaan</code></p>
<p>2.&nbsp;Traditional mediation analysis</p>
<p>3.&nbsp;Causal mediation analysis</p>
<p>4.&nbsp;Structural equation modeling</p>
<section id="front-end-matters" class="level1">
<h1>Front-end Matters</h1>
<p>The <code>mediation</code> and <code>lavaan</code> packages are essential tools for conducting <strong>mediation analysis</strong> and <strong>structural equation modeling (SEM)</strong> in R. The <code>mediation</code> package provides a framework for both traditional and causal mediation analysis, allowing researchers to estimate direct and indirect effects while accounting for confounding and sensitivity analyses. The <code>lavaan</code> package enables flexible SEM modeling, handling multiple mediators, latent variables, and complex causal pathways.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("mediation")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("lavaan")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sandwich</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>mediation: Causal Mediation Analysis
Version: 4.5.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-19
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
</div>
</section>
<section id="traditional-mediation-analysis" class="level1">
<h1>Traditional mediation analysis</h1>
<p>In this section, we perform traditional mediation analysis using Baron and Kenny’s method. This approach involves a three-step regression process to assess whether the effect of an independent variable on an outcome is mediated through an intermediate variable.</p>
<p>In this tutorial, we examine whether self-esteem serves as a mediator in the relationship between grades and happiness. In this dataset, X represents grades, Y represents happiness, and M represents self-esteem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>tradata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'http://static.lib.virginia.edu/statlab/materials/data/mediationData.csv'</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tradata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X M Y
1 6 5 6
2 7 5 5
3 7 7 4
4 8 4 8
5 4 3 5
6 4 4 7</code></pre>
</div>
</div>
<p><strong>Step 1</strong>, we want X to affect Y. If there is no relationship between X and Y, there is nothing to mediate. Although this is what Baron and Kenny originally suggested, this step is controversial. Even if we don’t find a significant association between X and Y, we could move forward to the next step if we have a good theoretical background about their relationship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>step1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X, tradata)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = tradata)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0262 -1.2340 -0.3282  1.5583  5.1622 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.8572     0.6932   4.122 7.88e-05 ***
X             0.3961     0.1112   3.564 0.000567 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.929 on 98 degrees of freedom
Multiple R-squared:  0.1147,    Adjusted R-squared:  0.1057 
F-statistic:  12.7 on 1 and 98 DF,  p-value: 0.0005671</code></pre>
</div>
</div>
<p>Since X has a significant impact on Y, we can move on to the next step: <strong>Step 2</strong>, we want X to affect M. If X and M have no relationship, M is just a third variable that may or may not be associated with Y. A mediation makes sense only if X affects M.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>step2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(M <span class="sc">~</span> X, tradata)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = M ~ X, data = tradata)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3046 -0.8656  0.1344  1.1344  4.6954 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.49952    0.58920   2.545   0.0125 *  
X            0.56102    0.09448   5.938 4.39e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.639 on 98 degrees of freedom
Multiple R-squared:  0.2646,    Adjusted R-squared:  0.2571 
F-statistic: 35.26 on 1 and 98 DF,  p-value: 4.391e-08</code></pre>
</div>
</div>
<p>Since X has a significant impact on M, we can move on to the next step: <strong>Step 3</strong>, we want M to affect Y, but X to no longer affect Y (or X to still affect Y but in a smaller magnitude). If a mediation effect exists, the effect of X on Y will disappear (or at least weaken) when M is included in the regression. The effect of X on Y goes through M.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>step3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X <span class="sc">+</span> M, tradata)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X + M, data = tradata)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7631 -1.2393  0.0308  1.0832  4.0055 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.9043     0.6055   3.145   0.0022 ** 
X             0.0396     0.1096   0.361   0.7187    
M             0.6355     0.1005   6.321 7.92e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.631 on 97 degrees of freedom
Multiple R-squared:  0.373, Adjusted R-squared:  0.3601 
F-statistic: 28.85 on 2 and 97 DF,  p-value: 1.471e-10</code></pre>
</div>
</div>
<p>If the effect of X on Y completely disappears, M fully mediates between X and Y (full mediation). If the effect of X on Y still exists, but in a smaller magnitude, M partially mediates between X and Y (partial mediation). The example shows a full mediation, yet a full mediation rarely happens in practice.</p>
<p>Once we find these relationships, we want to see if this mediation effect is statistically significant. To do so, there are two main approaches: the Sobel test and bootstrapping.</p>
<p>Sobel test is a parametric test used to determine whether the indirect effect (a × b) is statistically significant. It uses the standard errors of a (X → M) and b (M → Y) to compute a Z-score, testing if the indirect effect is significantly different from zero. Sobel test assumes normality of the indirect effect, and requires large sample size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: boot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>bda - 18.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients and standard errors</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">coef</span>(step2)[<span class="st">"X"</span>]  <span class="co"># Effect of X on M</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(step3)[<span class="st">"M"</span>]  <span class="co"># Effect of M on Y</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>sa <span class="ot">&lt;-</span> <span class="fu">summary</span>(step2)<span class="sc">$</span>coefficients[<span class="st">"X"</span>, <span class="st">"Std. Error"</span>]  <span class="co"># SE of a</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>sb <span class="ot">&lt;-</span> <span class="fu">summary</span>(step3)<span class="sc">$</span>coefficients[<span class="st">"M"</span>, <span class="st">"Std. Error"</span>]  <span class="co"># SE of b</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Sobel Test Calculation</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>sobel_z <span class="ot">&lt;-</span> (a <span class="sc">*</span> b) <span class="sc">/</span> <span class="fu">sqrt</span>((b<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> sa<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (a<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> sb<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>sobel_p <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(sobel_z)))  <span class="co"># Two-tailed p-value</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sobel Test Z-score:"</span>, sobel_z, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sobel Test Z-score: 4.327891 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sobel Test p-value:"</span>, sobel_p, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sobel Test p-value: 1.505439e-05 </code></pre>
</div>
</div>
<p>Bootstrapping, in contrast, is a non-parametric method that repeatedly resamples the dataset to create an empirical distribution of the mediation effect. Instead of assuming normality, it estimates confidence intervals (CIs) from thousands of resamples. Bootstrapping has key advantages including no normality assumption, higher statistical power, and works with small samples. Bootstrapping is strongly recommended in recent years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to compute indirect effect</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>indirect_effect <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]  <span class="co"># Resample data</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(M <span class="sc">~</span> X, <span class="at">data =</span> d))[<span class="st">"X"</span>]</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> X <span class="sc">+</span> M, <span class="at">data =</span> d))[<span class="st">"M"</span>]</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(a <span class="sc">*</span> b)  <span class="co"># Indirect effect</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform bootstrapping</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>boot_results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> tradata, <span class="at">statistic =</span> indirect_effect, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print bootstrapped confidence intervals</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(boot_results, <span class="at">type =</span> <span class="st">"perc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 1000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot_results, type = "perc")

Intervals : 
Level     Percentile     
95%   ( 0.2087,  0.5373 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<p>Both tests indicate a significant mediation effect. We conclude that <strong>Grades positively influence happiness by increasing self-esteem.</strong></p>
<p>However, traditional mediation analysis has key limitations – it relies on correlational assumptions and does not explicitly model counterfactual outcomes. This means that while we observe a mediation effect, we cannot make strong causal claims about whether self-esteem truly transmits the effect of grades on happiness.</p>
</section>
<section id="causal-mediation-analysis" class="level1">
<h1>Causal mediation analysis</h1>
<p>To address these limitations, we turn to causal mediation analysis, which is implemented in R using the mediation package. While the first steps look similar to Baron &amp; Kenny’s approach—fitting regression models for the mediator and outcome—the mediate() function goes beyond simple associations by using a counterfactual framework to estimate the <strong>Average Causal Mediation Effect (ACME)</strong> and <strong>Average Direct Effect (ADE)</strong>. This allows for a formal causal interpretation of mediation effects, assuming key assumptions hold.</p>
<section id="simple-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-model">Simple model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">mediate</span>(step2, step3, <span class="at">treat=</span><span class="st">'X'</span>, <span class="at">mediator=</span><span class="st">'M'</span>,<span class="at">boot=</span><span class="cn">TRUE</span>, <span class="at">sims=</span><span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Running nonparametric bootstrap</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

               Estimate 95% CI Lower 95% CI Upper p-value    
ACME             0.3565       0.2178         0.52  &lt;2e-16 ***
ADE              0.0396      -0.1911         0.29   0.696    
Total Effect     0.3961       0.1624         0.66   0.004 ** 
Prop. Mediated   0.9000       0.5019         2.01   0.004 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 100 


Simulations: 500 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial4_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>total effect</strong> in the summary is <span class="math inline">\(b_1\)</span> in the fist step: total effect of X on Y without M. The <strong>direct effect (ADE)</strong> is <span class="math inline">\(b_4\)</span> in the third step: a direct effect of X on Y after taking into account of a mediator effect of M. The <strong>mediation effect (ACME)</strong> is the total effect minus the direct effect (<span class="math inline">\(b_1-b_4\)</span>), which equals to the product of a coefficient of X in the second step and a coefficient of M in the last step (<span class="math inline">\(b_2*b_3\)</span>). The goal of mediation analysis is to obtain this mediation effect and see if it’s statistically significant.</p>
<p>Let’s look into a more complicated model. We’re using <em>job</em> data in <code>mediation</code> package.</p>
</section>
<section id="model-with-covariates" class="level2">
<h2 class="anchored" data-anchor-id="model-with-covariates">Model with covariates</h2>
<p>We use the <em>jobs</em> data from <code>mediation</code> package. This dataset is from the Job Search Intervention Study. In this dataset, people in the treatment group participated in job-skills workshops (treat). The outcome variable is a continuous measure of depressive symptoms (depress2). A continuous measure of job-search self efficacy represents a key mediating variable (job_seek). And we also have a list of covariates, including pre-treatment level of depression (depress1), education (educ), income, race(nonwhite), marital status (marrital), age, sex, previous occupation (occp), and the level of economic hardship (econ_hard).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"jobs"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(jobs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treat econ_hard depress1 sex      age                    occp marital
1     1      3.00     1.91   1 34.16712           professionals married
2     1      3.67     1.36   0 26.10137 operatives/kindred wrks nevmarr
3     1      4.00     2.09   1 35.02192 operatives/kindred wrks nevmarr
4     0      2.33     1.45   0 27.48767              manegerial married
5     1      1.33     1.73   1 31.61096        clerical/kindred separtd
6     1      3.00     1.55   0 40.43835              manegerial married
    nonwhite   educ income job_seek depress2  work1 comply control job_dich
1 non.white1 gradwk   50k+ 4.833333 1.727273 psyemp      0   treat        1
2     white0 somcol 15t24k 3.833333 2.000000 psyemp      0   treat        0
3 non.white1 somcol 25t39k 4.500000 2.181818 psyump      0   treat        1
4     white0   bach 25t39k 3.666667 1.545455 psyump      0 control        0
5 non.white1 highsc 25t39k 2.500000 2.363636 psyump      1   treat        0
6     white0 highsc   50k+ 4.000000 1.181818 psyump      1   treat        1
  job_disc
1        4
2        3
3        4
4        3
5        2
6        3</code></pre>
</div>
</div>
<p>For causal mediation analysis, we first estimate two linear regressions for both the mediator and the outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model.m <span class="ot">&lt;-</span> <span class="fu">lm</span>(job_seek <span class="sc">~</span> treat <span class="sc">+</span> depress1 <span class="sc">+</span> econ_hard <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> occp <span class="sc">+</span> marital <span class="sc">+</span> nonwhite <span class="sc">+</span> educ <span class="sc">+</span> income, <span class="at">data =</span> jobs)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model.y <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress2 <span class="sc">~</span> treat <span class="sc">+</span> job_seek <span class="sc">+</span> depress1 <span class="sc">+</span> econ_hard <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> occp <span class="sc">+</span> marital <span class="sc">+</span> nonwhite <span class="sc">+</span> educ <span class="sc">+</span> income, <span class="at">data =</span> jobs)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>out<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">mediate</span>(model.m, model.y, <span class="at">sims =</span> <span class="dv">1000</span>, <span class="at">boot =</span> <span class="cn">TRUE</span>, <span class="at">treat =</span> <span class="st">"treat"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="at">mediator =</span> <span class="st">"job_seek"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Running nonparametric bootstrap</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

               Estimate 95% CI Lower 95% CI Upper p-value  
ACME            -0.0137      -0.0321         0.00   0.078 .
ADE             -0.0368      -0.1189         0.04   0.360  
Total Effect    -0.0505      -0.1338         0.02   0.204  
Prop. Mediated   0.2718      -1.9019         3.35   0.254  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 899 


Simulations: 1000 </code></pre>
</div>
</div>
<p>The job-skills workshop reduces depressive symptoms, at least in part, by increasing job-seeking behavior.</p>
</section>
<section id="sensitivity" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity">Sensitivity</h2>
<p>We can quickly run a sensitivity analysis using the <code>medsens()</code> function from the mediation package. This will help assess how unmeasured confounding between the mediator (job_seek) and outcome (depress2) could affect your results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sens.out <span class="ot">&lt;-</span> <span class="fu">medsens</span>(out<span class="fl">.1</span>, <span class="at">sims =</span> <span class="dv">1000</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sens.out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mediation Sensitivity Analysis for Average Causal Mediation Effect

Sensitivity Region

       Rho    ACME 95% CI Lower 95% CI Upper R^2_M*R^2_Y* R^2_M~R^2_Y~
 [1,] -0.9  0.1183      -0.0274       0.2640         0.81       0.5293
 [2,] -0.8  0.0715      -0.0166       0.1597         0.64       0.4182
 [3,] -0.7  0.0489      -0.0115       0.1093         0.49       0.3202
 [4,] -0.6  0.0342      -0.0081       0.0766         0.36       0.2353
 [5,] -0.5  0.0232      -0.0057       0.0520         0.25       0.1634
 [6,] -0.4  0.0142      -0.0038       0.0321         0.16       0.1046
 [7,] -0.3  0.0064      -0.0025       0.0153         0.09       0.0588
 [8,] -0.2 -0.0007      -0.0049       0.0036         0.04       0.0261
 [9,] -0.1 -0.0073      -0.0172       0.0026         0.01       0.0065
[10,]  0.0 -0.0137      -0.0312       0.0037         0.00       0.0000
[11,]  0.1 -0.0202      -0.0453       0.0050         0.01       0.0065
[12,]  0.2 -0.0268      -0.0600       0.0065         0.04       0.0261
[13,]  0.3 -0.0338      -0.0757       0.0080         0.09       0.0588
[14,]  0.4 -0.0416      -0.0931       0.0098         0.16       0.1046
[15,]  0.5 -0.0507      -0.1132       0.0118         0.25       0.1634
[16,]  0.6 -0.0617      -0.1378       0.0144         0.36       0.2353
[17,]  0.7 -0.0764      -0.1706       0.0177         0.49       0.3202
[18,]  0.8 -0.0990      -0.2209       0.0229         0.64       0.4182
[19,]  0.9 -0.1458      -0.3252       0.0337         0.81       0.5293

Rho at which ACME = 0: -0.2
R^2_M*R^2_Y* at which ACME = 0: 0.04
R^2_M~R^2_Y~ at which ACME = 0: 0.0261 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sens.out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial4_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>ρ (rho) represents the correlation between residual confounders that affect both the mediator (job_seek) and the outcome (depress2). ρ = -0.2 means that for the mediation effect (ACME) to completely disappear, an unmeasured confounder would need to create a correlation of -0.2 between the errors in M and Y. Since ρ = -0.2 is relatively small, the mediation effect is somewhat sensitive to hidden confounders.</p>
<p>The graph shows how fast ACME approaches 0 as ρ increases. If the ACME estimate does not change much across different rho values, it means that the mediation effect is not highly sensitive to hidden confounding. In contrast, if ACME drops to zero (or changes drastically) with a small shift in rho, it indicates that even a small amount of unmeasured confounding could invalidate the mediation effect.</p>
</section>
<section id="mediator-is-also-moderator" class="level2">
<h2 class="anchored" data-anchor-id="mediator-is-also-moderator">Mediator is also moderator</h2>
<p>We can also allow the causal mediation effect to vary with treatment status. Here, the <strong>model for the outcome</strong> must be altered by including an interaction term between the treatment indicator (treat) and the mediator variable (job_seek)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>model.y.inter <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress2 <span class="sc">~</span> treat <span class="sc">+</span> job_seek <span class="sc">+</span> treat<span class="sc">:</span>job_seek <span class="sc">+</span> depress1 <span class="sc">+</span> econ_hard <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> occp <span class="sc">+</span> marital <span class="sc">+</span> nonwhite <span class="sc">+</span> educ <span class="sc">+</span> income, <span class="at">data =</span> jobs)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>out<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">mediate</span>(model.m, model.y.inter, <span class="at">sims =</span> <span class="dv">1000</span>, <span class="at">boot =</span> <span class="cn">TRUE</span>, <span class="at">treat =</span> <span class="st">"treat"</span>, <span class="at">mediator =</span> <span class="st">"job_seek"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Running nonparametric bootstrap</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

                         Estimate 95% CI Lower 95% CI Upper p-value
ACME (control)            -0.0185      -0.0451         0.00    0.10
ACME (treated)            -0.0117      -0.0298         0.00    0.10
ADE (control)             -0.0356      -0.1304         0.04    0.34
ADE (treated)             -0.0288      -0.1235         0.05    0.42
Total Effect              -0.0473      -0.1424         0.03    0.21
Prop. Mediated (control)   0.3920      -1.7387         3.50    0.26
Prop. Mediated (treated)   0.2482      -1.1572         2.35    0.26
ACME (average)            -0.0151      -0.0352         0.00    0.10
ADE (average)             -0.0322      -0.1251         0.04    0.38
Prop. Mediated (average)   0.3201      -1.3863         2.97    0.26

Sample Size Used: 899 


Simulations: 1000 </code></pre>
</div>
</div>
<p>Now estimates for the mediation effects, direct effects and proportion of total effect mediated correspond to the levels of the treatment. In this case, the mediation effect under the treatment condition, listed as ACME (treated) is estimated to be −.012, while the mediation effect under the control condition, ACME (control), is −.019.</p>
<p>Both ACME values are negative, indicating that job-seeking behavior reduces depressive symptoms, regardless of whether individuals received treatment. However, the absolute value of ACME is larger for the control group (-0.0185) than for the treated group (-0.0117). This suggests that the indirect effect of job-seeking on depression is stronger when individuals did NOT receive treatment.</p>
<p>When having a <em>mediate</em> object with interaction, we can select which treatment condition to plot the estimated effects for by selecting the <em>treatment</em> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(out<span class="fl">.2</span>, <span class="at">treatment =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial4_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(out.2, treatment = "treated")</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(out.2, treatment = "control")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Solid lines represent treated group, and dotted lines represent control group. We can also make sensitivity plots for different treatment conditions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>sens.out<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">medsens</span>(out<span class="fl">.2</span>, <span class="at">sims =</span> <span class="dv">1000</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sens.out<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mediation Sensitivity Analysis: Average Mediation Effect

Sensitivity Region: ACME for Control Group

       Rho ACME(control) 95% CI Lower 95% CI Upper R^2_M*R^2_Y* R^2_M~R^2_Y~
 [1,] -0.9        0.1133      -0.0264       0.2530         0.81       0.5279
 [2,] -0.8        0.0666      -0.0157       0.1489         0.64       0.4171
 [3,] -0.7        0.0441      -0.0107       0.0988         0.49       0.3194
 [4,] -0.6        0.0294      -0.0075       0.0662         0.36       0.2346
 [5,] -0.5        0.0183      -0.0054       0.0421         0.25       0.1629
 [6,] -0.4        0.0093      -0.0043       0.0230         0.16       0.1043
 [7,] -0.3        0.0015      -0.0061       0.0092         0.09       0.0587
 [8,] -0.2       -0.0055      -0.0155       0.0045         0.04       0.0261
 [9,] -0.1       -0.0121      -0.0288       0.0045         0.01       0.0065
[10,]  0.0       -0.0185      -0.0425       0.0055         0.00       0.0000
[11,]  0.1       -0.0250      -0.0566       0.0066         0.01       0.0065
[12,]  0.2       -0.0316      -0.0712       0.0080         0.04       0.0261
[13,]  0.3       -0.0386      -0.0868       0.0095         0.09       0.0587
[14,]  0.4       -0.0464      -0.1040       0.0112         0.16       0.1043
[15,]  0.5       -0.0554      -0.1240       0.0132         0.25       0.1629
[16,]  0.6       -0.0664      -0.1486       0.0157         0.36       0.2346
[17,]  0.7       -0.0811      -0.1813       0.0190         0.49       0.3194
[18,]  0.8       -0.1037      -0.2316       0.0242         0.64       0.4171
[19,]  0.9       -0.1504      -0.3357       0.0349         0.81       0.5279

Rho at which ACME for Control Group = 0: -0.3
R^2_M*R^2_Y* at which ACME for Control Group = 0: 0.09
R^2_M~R^2_Y~ at which ACME for Control Group = 0: 0.0587 


Sensitivity Region: ACME for Treatment Group

       Rho ACME(treated) 95% CI Lower 95% CI Upper R^2_M*R^2_Y* R^2_M~R^2_Y~
 [1,] -0.9        0.1201      -0.0278       0.2681         0.81       0.5279
 [2,] -0.8        0.0734      -0.0171       0.1639         0.64       0.4171
 [3,] -0.7        0.0509      -0.0119       0.1137         0.49       0.3194
 [4,] -0.6        0.0362      -0.0086       0.0809         0.36       0.2346
 [5,] -0.5        0.0251      -0.0062       0.0564         0.25       0.1629
 [6,] -0.4        0.0161      -0.0043       0.0366         0.16       0.1043
 [7,] -0.3        0.0083      -0.0030       0.0197         0.09       0.0587
 [8,] -0.2        0.0013      -0.0038       0.0064         0.04       0.0261
 [9,] -0.1       -0.0053      -0.0135       0.0029         0.01       0.0065
[10,]  0.0       -0.0117      -0.0270       0.0035         0.00       0.0000
[11,]  0.1       -0.0182      -0.0410       0.0047         0.01       0.0065
[12,]  0.2       -0.0248      -0.0557       0.0061         0.04       0.0261
[13,]  0.3       -0.0318      -0.0713       0.0077         0.09       0.0587
[14,]  0.4       -0.0396      -0.0886       0.0094         0.16       0.1043
[15,]  0.5       -0.0486      -0.1087       0.0114         0.25       0.1629
[16,]  0.6       -0.0596      -0.1332       0.0139         0.36       0.2346
[17,]  0.7       -0.0743      -0.1660       0.0173         0.49       0.3194
[18,]  0.8       -0.0969      -0.2163       0.0225         0.64       0.4171
[19,]  0.9       -0.1436      -0.3204       0.0332         0.81       0.5279

Rho at which ACME for Treatment Group = 0: -0.2
R^2_M*R^2_Y* at which ACME for Treatment Group = 0: 0.04
R^2_M~R^2_Y~ at which ACME for Treatment Group = 0: 0.0261 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sens.out<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tutorial4_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>mediation</code> package is not limited to OLS models; it also supports mediation analysis for binary, ordinal, and other types of dependent variables, making it highly flexible for different study designs. For more details and documentation, visit the <a href="https://cran.r-project.org/web/packages/mediation/mediation.pdf">mediation</a> package website.</p>
</section>
</section>
<section id="structural-equation-modeling-sem" class="level1">
<h1>Structural Equation Modeling (SEM)</h1>
<p>Structural Equation Modeling (SEM) is a powerful statistical framework that allows for estimating complex relationships among variables, including mediation effects. Unlike traditional mediation analysis, SEM enables researchers to simultaneously model multiple mediators, assess indirect and direct effects, and incorporate more flexible model specifications. In this tutorial, we focus on multiple mediation models, specifically <strong>parallel mediation</strong> (where multiple mediators operate independently) and <strong>sequential mediation</strong> (where mediators influence each other in a chain before affecting the outcome). By using SEM, we can gain deeper insights into how multiple pathways contribute to the overall effect of an independent variable on an outcome.</p>
<p>The data we are using is downloaded from <a href="https://drive.google.com/file/d/1Adn0FP1E82v2moLupRAj8EZZ3O09CtaT/view">here</a>. Make sure you download the data before running the tutorial.</p>
<p>This data includes independent variable (<em>mastery</em> goal), outcome (<em>achieve</em>ment), and multiple mediating variables, such as interest and anxiety.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>SEMdata <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"regression data.xls"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(SEMdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
    ïid perfgoal achieve mastery interest anxiety genderid masterylmh
  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1     1     32      6.12    5.71      6      1.67        1          3
2     2     32.3    1.62    1.43      4      6.33        1          1
3     3     37.9    4.5     1.29      2      3.67        1          1
4     4     58.1    2.38    2.29      4      3.67        1          2
5     5     26.7    5.12    4.57      5.5    3.67        0          3
6     6     50.6    3.38    1.86      4      6.33        1          2
# ℹ 2 more variables: perfgoallmh &lt;dbl&gt;, interestms &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="parallel-mediation" class="level2">
<h2 class="anchored" data-anchor-id="parallel-mediation">Parallel mediation</h2>
<p>In parallel mediation, multiple mediators operate independently to explain the effect of an independent variable (X) on an outcome (Y). This means that each mediator contributes separately to the total mediation effect, without influencing each other.</p>
<p>We first write down the model specifying all relationships. The indirect effects are defined to capture the mediation pathways: one through <strong>interest</strong> (mstr_int_achv = a × b) and another through <strong>anxiety</strong> (mstr_anxt_achv = c × d). The total effect combines all direct and indirect effects, allowing us to assess the full impact of mastery on achievement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">"achieve ~ b*interest + d*anxiety + e*mastery</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="st">          interest ~ a*mastery</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="st">          anxiety ~ c*mastery</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="st">          mstr_int_achv := a*b</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="st">          mstr_anxt_achv := c*d</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="st">          Total := a*b + c*d + e</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <code>lavaan</code>, the <code>:=</code> operator is used to define custom parameters based on existing model estimates. This is particularly useful in mediation analysis, where indirect effects need to be explicitly computed from path coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(model, <span class="at">data =</span> SEMdata, <span class="at">se=</span><span class="st">"bootstrap"</span>, <span class="at">bootstrap =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: lavaan-&gt;lav_model_nvcov_bootstrap():  
   1 bootstrap runs failed or did not converge.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit, <span class="at">fit.measures =</span> T, <span class="at">standardized =</span> T, <span class="at">rsquare =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         8

  Number of observations                           140

Model Test User Model:
                                                      
  Test statistic                                 0.010
  Degrees of freedom                                 1
  P-value (Chi-square)                           0.920

Model Test Baseline Model:

  Test statistic                               149.860
  Degrees of freedom                                 6
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.041

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -704.422
  Loglikelihood unrestricted model (H1)       -704.417
                                                      
  Akaike (AIC)                                1424.844
  Bayesian (BIC)                              1448.377
  Sample-size adjusted Bayesian (SABIC)       1423.066

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.082
  P-value H_0: RMSEA &lt;= 0.050                    0.933
  P-value H_0: RMSEA &gt;= 0.080                    0.051

Standardized Root Mean Square Residual:

  SRMR                                           0.002

Parameter Estimates:

  Standard errors                            Bootstrap
  Number of requested bootstrap draws             1000
  Number of successful bootstrap draws             999

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  achieve ~                                                             
    interest   (b)    0.211    0.072    2.935    0.003    0.211    0.294
    anxiety    (d)   -0.040    0.056   -0.722    0.470   -0.040   -0.053
    mastery    (e)    0.345    0.096    3.591    0.000    0.345    0.379
  interest ~                                                            
    mastery    (a)    0.770    0.083    9.319    0.000    0.770    0.607
  anxiety ~                                                             
    mastery    (c)   -0.399    0.090   -4.436    0.000   -0.399   -0.337

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .achieve           0.988    0.102    9.737    0.000    0.988    0.613
   .interest          1.973    0.229    8.609    0.000    1.973    0.631
   .anxiety           2.415    0.211   11.439    0.000    2.415    0.886

R-Square:
                   Estimate
    achieve           0.387
    interest          0.369
    anxiety           0.114

Defined Parameters:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    mstr_int_achv     0.162    0.057    2.856    0.004    0.162    0.178
    mstr_anxt_achv    0.016    0.023    0.692    0.489    0.016    0.018
    Total             0.524    0.067    7.776    0.000    0.524    0.575</code></pre>
</div>
</div>
<p>Results indicate that mastery goal has indirect effect of 0.162 on achievement through interest. But mastery goal doesn’t have indirect effect on achievement through anxiety. Mastery goal has total effect of 0.524 on achievement.</p>
</section>
<section id="sequential-mediation" class="level2">
<h2 class="anchored" data-anchor-id="sequential-mediation">Sequential mediation</h2>
<p>In sequential mediation, the mediators are causally dependent on each other, forming a chain-like process where the effect of the independent variable (X) is transmitted through multiple steps before reaching the outcome (Y). Unlike parallel mediation, where mediators operate independently, sequential mediation assumes that <strong>one mediator influences another</strong> before affecting Y. This allows researchers to explore how intermediate mechanisms unfold over time. For example, in an educational setting, mastery might first enhance interest, which then reduces anxiety, ultimately leading to higher achievement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="st">"achieve ~ c*anxiety + e*interest + f*mastery</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="st">           interest ~ a*mastery</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="st">           anxiety ~ b*interest + d*mastery</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="st">           mstr_int_anxt_achv := a*b*c</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="st">           mstr_int_achv := a*e</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="st">           mstr_anxt_achv := d*c</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="st">           int_anxt_achv := b*c</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="st">           total_mstr := a*b*c + a*e + d*c + f</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="st">           total_int := b*c + e</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that in sequential mediation, it is not enough to only compute the total and indirect effects of the initial treatment variable (mastery). Since mediators influence one another in a chain, we must also consider the total and indirect effects of the first mediator (interest) to fully capture the mediation process.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(model2, <span class="at">data =</span> SEMdata, <span class="at">se=</span><span class="st">"bootstrap"</span>, <span class="at">bootstrap =</span> <span class="dv">1000</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2, <span class="at">fit.measures =</span> T, <span class="at">standardized =</span> T, <span class="at">rsquare =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         9

  Number of observations                           140

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Model Test Baseline Model:

  Test statistic                               149.860
  Degrees of freedom                                 6
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.000

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -704.417
  Loglikelihood unrestricted model (H1)       -704.417
                                                      
  Akaike (AIC)                                1426.834
  Bayesian (BIC)                              1453.309
  Sample-size adjusted Bayesian (SABIC)       1424.834

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.000
  P-value H_0: RMSEA &lt;= 0.050                       NA
  P-value H_0: RMSEA &gt;= 0.080                       NA

Standardized Root Mean Square Residual:

  SRMR                                           0.000

Parameter Estimates:

  Standard errors                            Bootstrap
  Number of requested bootstrap draws             1000
  Number of successful bootstrap draws            1000

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  achieve ~                                                             
    anxiety    (c)   -0.040    0.056   -0.723    0.470   -0.040   -0.053
    interest   (e)    0.211    0.072    2.933    0.003    0.211    0.294
    mastery    (f)    0.345    0.096    3.592    0.000    0.345    0.379
  interest ~                                                            
    mastery    (a)    0.770    0.083    9.310    0.000    0.770    0.607
  anxiety ~                                                             
    interest   (b)    0.009    0.099    0.095    0.924    0.009    0.010
    mastery    (d)   -0.406    0.116   -3.508    0.000   -0.406   -0.343

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .achieve           0.988    0.101    9.741    0.000    0.988    0.613
   .interest          1.973    0.229    8.606    0.000    1.973    0.631
   .anxiety           2.415    0.212   11.382    0.000    2.415    0.886

R-Square:
                   Estimate
    achieve           0.387
    interest          0.369
    anxiety           0.114

Defined Parameters:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    mstr_nt_nxt_ch   -0.000    0.006   -0.052    0.958   -0.000   -0.000
    mstr_int_achv     0.162    0.057    2.857    0.004    0.162    0.178
    mstr_anxt_achv    0.016    0.023    0.701    0.484    0.016    0.018
    int_anxt_achv    -0.000    0.007   -0.053    0.958   -0.000   -0.001
    total_mstr        0.524    0.067    7.778    0.000    0.524    0.575
    total_int         0.211    0.071    2.952    0.003    0.211    0.293</code></pre>
</div>
</div>
<p>Results indicate that mastery goal has indirect effect of 0.162 on achievement through interest. But this indirect effect does not happen through anxiety. Mastery goal also show a total effect of 0.524 on achievement.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this tutorial, we explored different approaches of mediation analysis, starting with traditional mediation analysis using the Baron and Kenny method, followed by causal mediation analysis and <code>mediation</code> package, which provides a counterfactual framework for estimating indirect effects. Finally, we applied Structural Equation Modeling (SEM) to mediation, focusing on parallel and sequential mediation models. SEM enables simultaneous estimation of multiple pathways, providing a more comprehensive framework for analyzing mediation effects. By combining these methods, we can better understand complex causal relationships and refine mediation analysis in research.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>